// <auto-generated />
using System;
using BlazorAppDemo.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521050617_20260521DB")]
    partial class _20260521DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppDemo.Components.Data.DefineDB.ActiveRecordInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveKind")
                        .HasColumnType("int");

                    b.Property<string>("ActiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<decimal?>("RunningDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Set")
                        .HasColumnType("int");

                    b.Property<decimal?>("Time")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ActiveRecords");
                });

            modelBuilder.Entity("BlazorAppDemo.Components.Data.DefineDB.FoodCompositionTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Bcarotene")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Carbohydrate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Energy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FoodCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Retinol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaltEquivalent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminB1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminB2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WasteRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("BlazorAppDemo.Components.Data.DefineDB.MealRecordInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MealRecords");
                });

            modelBuilder.Entity("BlazorAppDemo.Components.Data.DefineDB.MenulInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaterialWeight")
                        .HasColumnType("float");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaltEquivalent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VitaminA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminB1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminB2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VitaminE")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuRecords");
                });

            modelBuilder.Entity("BlazorAppDemo.Components.Data.DefineDB.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("BasalMetabolism")
                        .HasColumnType("float");

                    b.Property<double>("BodyWeight")
                        .HasColumnType("float");

                    b.Property<double>("Bodyheight")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhysicalActivityLevel")
                        .HasColumnType("float");

                    b.Property<double>("TotalDailyEnergyExpenditure")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInfoRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
